### Evolutionary Dynamics Visualization

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
# Utility matrix for 2 player symmetric game
A = np.array([[0, 5, 4],
             [4, 0, 5],
             [5, 4, 0]])
# Initial point
x_start = np.array([0.25, 0.5, 0.25])

# List of parameter nabla for logit dynamics
etta = np.array([0.01, 0.1, 1])

#### a) Replicator Dynamics

In [17]:
def replicator_dynamics(x_initial, num_iter, matrix, learning_rate=1e-3):
    """ Function that returns list of coordinates given replicator dynamics and initial point

    Args:
        x_initial: Starting point
        num_iter: Number of iterations
        matrix: symmetric game matrix
    Returns:
        List of x coordinates of length num_iter

    """
    x_curr = x_initial.copy()
    positions = []
    
    for i in range(num_iter):
        positions.append(x_curr.copy())
        f = np.matmul(matrix, x_curr)
        avg_payoff = np.matmul(np.transpose(x_curr), f)  # Average payoff
        f_bar = np.multiply(avg_payoff, np.ones(3))  # Average payoff vector
        x_dot = np.multiply(x_curr, (f - f_bar))  # Displacement vector
        x_curr += learning_rate * x_dot  # Update position
        
    return positions  

In [18]:
max_iter = 5000
coords_a = replicator_dynamics(x_start, max_iter, A)

In [6]:
""" 
INSERT CODE TO PLOT HERE

"""

' \nINSERT CODE TO PLOT HERE\n\n'

#### b) BNN Dynamics

In [34]:
def bnn_dynamics(x_initial, num_iter, matrix, learning_rate=1e-3):
    """ Function that returns list of coordinates given BNN dynamics and initial point

    Args:
        x_initial: Starting point
        num_iter: Number of iterations
        matrix: symmetric game matrix
    Returns:
        List of x coordinates of length num_iter

    """
    x_curr = x_initial.copy()
    positions = []
    
    for i in range(num_iter):
        positions.append(x_curr.copy())
        f = np.matmul(matrix, x_curr)
        avg_payoff = np.matmul(np.transpose(x_curr), f)  # Average payoff
        f_bar = np.multiply(avg_payoff, np.ones(3))  # Average payoff vector
        pi_hat_plus = np.maximum((f-f_bar),np.zeros(3)) # sign function pi_hat
        x_dot = pi_hat_plus - np.multiply(x_curr, pi_hat_plus.sum())  # Displacement vector
        x_curr += learning_rate * x_dot  # Update position
        
    return positions  

In [37]:
max_iter = 500
coords_b = bnn_dynamics(x_start, max_iter, A, 1e-2)

In [38]:
coords_b

[array([0.25, 0.5 , 0.25]),
 array([0.2540625, 0.494375 , 0.2515625]),
 array([0.25786055, 0.48905513, 0.25308432]),
 array([0.26141649, 0.48401491, 0.2545686 ]),
 array([0.26475026, 0.47923178, 0.25601796]),
 array([0.26787964, 0.4746857 , 0.25743466]),
 array([0.27082063, 0.47035877, 0.2588206 ]),
 array([0.27358762, 0.46623496, 0.26017742]),
 array([0.27619362, 0.46229984, 0.26150654]),
 array([0.27865041, 0.45854042, 0.26280918]),
 array([0.28096867, 0.45494491, 0.26408641]),
 array([0.28315817, 0.45150265, 0.26533917]),
 array([0.28522779, 0.44820391, 0.2665683 ]),
 array([0.28718567, 0.44503982, 0.26777452]),
 array([0.28903925, 0.44200225, 0.2689585 ]),
 array([0.2907954 , 0.43908377, 0.27012083]),
 array([0.2924604 , 0.43627754, 0.27126206]),
 array([0.29404005, 0.43357726, 0.27238268]),
 array([0.29553973, 0.43097711, 0.27348316]),
 array([0.29696437, 0.42847173, 0.27456391]),
 array([0.29831856, 0.42605611, 0.27562533]),
 array([0.29960654, 0.42372566, 0.2766678 ]),
 array([0