### Evolutionary Dynamics Visualization

In [40]:
import numpy as np
import matplotlib.pyplot as plt

In [41]:
# Utility matrix for 2 player symmetric game
A = np.array([[0, 5, 4],
             [4, 0, 5],
             [5, 4, 0]])
# Initial point
x_start = np.array([0.25, 0.5, 0.25])

# List of parameter nabla for logit dynamics
etta = np.array([0.01, 0.1, 1])

#### a) Replicator Dynamics

In [59]:
def replicator_dynamics(x_initial, num_iter, matrix, learning_rate=1e-3, early_stopping=True):
    """ Function that returns list of replicator dynamic coordinates given an initial point

    Args:
        x_initial: Starting point
        num_iter: Number of iterations
        matrix: symmetric game matrix
    Returns:
        List of x coordinates of length num_iter

    """
    x_curr = x_initial.copy()
    positions = []
    
    for i in range(num_iter):
        positions.append(x_curr.copy())
        f = np.matmul(matrix, x_curr)
        avg_payoff = np.matmul(np.transpose(x_curr), f)  # Average payoff
        f_bar = np.multiply(avg_payoff, np.ones(3))  # Average payoff vector
        x_dot = np.multiply(x_curr, (f - f_bar))  # Displacement vector
        x_curr += learning_rate * x_dot  # Update position
        
    return positions  

In [62]:
max_iter = 5000
coords_a = replicator_dynamics(x_start, max_iter, A)

In [65]:
coords_a[3000:4999]

[array([0.33397122, 0.33429665, 0.33173212]),
 array([0.3339707 , 0.33429484, 0.33173447]),
 array([0.33397017, 0.33429302, 0.33173681]),
 array([0.33396965, 0.33429121, 0.33173914]),
 array([0.33396912, 0.3342894 , 0.33174147]),
 array([0.3339686, 0.3342876, 0.3317438]),
 array([0.33396808, 0.3342858 , 0.33174613]),
 array([0.33396755, 0.334284  , 0.33174845]),
 array([0.33396703, 0.3342822 , 0.33175077]),
 array([0.3339665 , 0.33428041, 0.33175309]),
 array([0.33396598, 0.33427862, 0.3317554 ]),
 array([0.33396546, 0.33427684, 0.33175771]),
 array([0.33396493, 0.33427505, 0.33176001]),
 array([0.33396441, 0.33427327, 0.33176232]),
 array([0.33396388, 0.3342715 , 0.33176462]),
 array([0.33396336, 0.33426973, 0.33176691]),
 array([0.33396284, 0.33426796, 0.33176921]),
 array([0.33396232, 0.33426619, 0.3317715 ]),
 array([0.33396179, 0.33426442, 0.33177378]),
 array([0.33396127, 0.33426266, 0.33177607]),
 array([0.33396075, 0.33426091, 0.33177835]),
 array([0.33396022, 0.33425915, 0.331