### Evolutionary Dynamics Visualization

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Utility matrix for 2 player symmetric game
A = np.array([[0, 5, 4],
             [4, 0, 5],
             [5, 4, 0]])
# Initial point
x_initial = np.array([0.25, 0.5, 0.25])

# List of parameter nabla for logit dynamics
eta = np.array([0.01, 0.1, 1])

#### a) Replicator Dynamics

In [18]:
def replicator_dynamics(x_init, num_iter, matrix, learning_rate=1e-3, early_stopping=True):
    """ Function that returns list of replicator dynamic coordinates given an initial point

    Args:
        x_init: Starting point
        max_iter: Number of iterations
        matrix: symmetric game matrix

    Returns:
        List of x coordinates of length num_iter

    """
    x_current = x_init
    positions = []
    
    for i in range(num_iter - 1):
        f = np.matmul(matrix, x_current)
        avg_payoff = np.matmul(np.transpose(x_current), f)  # Average payoff
        f_bar = np.multiply(avg_payoff, np.ones(3))  # Average payoff vector
        x_dot = np.multiply(x_current, (f - f_bar))  # Displacement vector
        positions.append(x_current)
        print(x_current)
        x_current += learning_rate * x_dot  # Update position
        
    
    return positions  

In [19]:
max_iter = 10000
x0 =  np.array([0.25, 0.5, 0.25])
coords = replicator_dynamics(x0, max_iter, A)

[0.25 0.5  0.25]
[0.25017187 0.49971875 0.25010938]
[0.25034347 0.49943796 0.25021857]
[0.25051478 0.49915763 0.2503276 ]
[0.25068581 0.49887775 0.25043644]
[0.25085655 0.49859834 0.25054511]
[0.25102702 0.49831938 0.25065361]
[0.2511972  0.49804087 0.25076193]
[0.2513671  0.49776282 0.25087007]
[0.25153673 0.49748523 0.25097804]
[0.25170607 0.49720809 0.25108584]
[0.25187513 0.49693141 0.25119346]
[0.2520439  0.49665518 0.25130092]
[0.2522124  0.4963794  0.25140819]
[0.25238062 0.49610408 0.2515153 ]
[0.25254856 0.4958292  0.25162223]
[0.25271622 0.49555478 0.251729  ]
[0.2528836  0.49528081 0.25183559]
[0.2530507  0.49500729 0.25194201]
[0.25321752 0.49473422 0.25204825]
[0.25338407 0.4944616  0.25215433]
[0.25355033 0.49418943 0.25226024]
[0.25371632 0.4939177  0.25236598]
[0.25388202 0.49364642 0.25247155]
[0.25404745 0.49337559 0.25257695]
[0.2542126  0.49310521 0.25268219]
[0.25437748 0.49283527 0.25278725]
[0.25454208 0.49256578 0.25289215]
[0.2547064  0.49229673 0.25299688]
[0.

[0.31364417 0.39141656 0.29493927]
[0.31369448 0.39131982 0.29498571]
[0.31374468 0.39122324 0.29503209]
[0.31379477 0.39112682 0.29507842]
[0.31384475 0.39103056 0.29512469]
[0.31389462 0.39093447 0.29517091]
[0.31394439 0.39083855 0.29521707]
[0.31399404 0.39074278 0.29526318]
[0.31404359 0.39064718 0.29530923]
[0.31409303 0.39055173 0.29535523]
[0.31414237 0.39045645 0.29540118]
[0.31419159 0.39036134 0.29544707]
[0.31424071 0.39026638 0.29549291]
[0.31428973 0.39017158 0.29553869]
[0.31433863 0.39007695 0.29558442]
[0.31438743 0.38998247 0.2956301 ]
[0.31443613 0.38988815 0.29567572]
[0.31448472 0.389794   0.29572129]
[0.3145332 0.3897    0.2957668]
[0.31458158 0.38960616 0.29581226]
[0.31462985 0.38951248 0.29585767]
[0.31467802 0.38941896 0.29590302]
[0.31472608 0.3893256  0.29594832]
[0.31477403 0.3892324  0.29599357]
[0.31482189 0.38913935 0.29603876]
[0.31486963 0.38904646 0.2960839 ]
[0.31491728 0.38895373 0.29612899]
[0.31496482 0.38886116 0.29617403]
[0.31501225 0.38876874 

[0.329908   0.35557453 0.31451747]
[0.32992114 0.35553758 0.31454128]
[0.32993424 0.35550069 0.31456507]
[0.32994731 0.35546387 0.31458882]
[0.32996035 0.3554271  0.31461255]
[0.32997335 0.3553904  0.31463625]
[0.32998632 0.35535375 0.31465993]
[0.32999926 0.35531717 0.31468357]
[0.33001217 0.35528064 0.31470719]
[0.33002504 0.35524418 0.31473078]
[0.33003788 0.35520777 0.31475435]
[0.33005069 0.35517143 0.31477788]
[0.33006347 0.35513514 0.31480139]
[0.33007621 0.35509891 0.31482487]
[0.33008893 0.35506275 0.31484833]
[0.33010161 0.35502664 0.31487175]
[0.33011426 0.35499059 0.31489515]
[0.33012688 0.3549546  0.31491852]
[0.33013946 0.35491867 0.31494187]
[0.33015201 0.3548828  0.31496518]
[0.33016454 0.35484699 0.31498847]
[0.33017703 0.35481124 0.31501174]
[0.33018949 0.35477554 0.31503497]
[0.33020191 0.35473991 0.31505818]
[0.33021431 0.35470433 0.31508136]
[0.33022667 0.35466881 0.31510452]
[0.33023901 0.35463335 0.31512764]
[0.33025131 0.35459794 0.31515074]
[0.33026358 0.354562

[0.33337478 0.34376965 0.32285557]
[0.33337853 0.34375203 0.32286943]
[0.33338227 0.34373445 0.32288328]
[0.333386   0.34371689 0.32289711]
[0.33338972 0.34369936 0.32291092]
[0.33339342 0.34368186 0.32292471]
[0.33339712 0.34366439 0.32293849]
[0.3334008  0.34364695 0.32295225]
[0.33340447 0.34362954 0.32296599]
[0.33340813 0.34361215 0.32297972]
[0.33341177 0.3435948  0.32299343]
[0.33341541 0.34357747 0.32300712]
[0.33341903 0.34356017 0.3230208 ]
[0.33342264 0.3435429  0.32303446]
[0.33342624 0.34352566 0.3230481 ]
[0.33342983 0.34350844 0.32306172]
[0.33343341 0.34349126 0.32307533]
[0.33343698 0.3434741  0.32308893]
[0.33344053 0.34345697 0.3231025 ]
[0.33344408 0.34343987 0.32311606]
[0.33344761 0.34342279 0.3231296 ]
[0.33345113 0.34340575 0.32314312]
[0.33345464 0.34338873 0.32315663]
[0.33345814 0.34337174 0.32317012]
[0.33346162 0.34335478 0.3231836 ]
[0.3334651  0.34333784 0.32319706]
[0.33346856 0.34332094 0.3232105 ]
[0.33347202 0.34330406 0.32322392]
[0.33347546 0.343287

[0.33423378 0.33764938 0.32811684]
[0.33423409 0.33764186 0.32812405]
[0.33423439 0.33763436 0.32813125]
[0.3342347  0.33762686 0.32813844]
[0.334235   0.33761938 0.32814562]
[0.33423529 0.33761191 0.3281528 ]
[0.33423559 0.33760445 0.32815996]
[0.33423588 0.33759701 0.32816712]
[0.33423616 0.33758958 0.32817426]
[0.33423645 0.33758216 0.3281814 ]
[0.33423673 0.33757475 0.32818852]
[0.33423701 0.33756735 0.32819564]
[0.33423728 0.33755997 0.32820275]
[0.33423755 0.3375526  0.32820985]
[0.33423782 0.33754524 0.32821694]
[0.33423809 0.3375379  0.32822402]
[0.33423835 0.33753056 0.32823109]
[0.33423861 0.33752324 0.32823815]
[0.33423887 0.33751593 0.3282452 ]
[0.33423912 0.33750864 0.32825224]
[0.33423937 0.33750135 0.32825928]
[0.33423962 0.33749408 0.3282663 ]
[0.33423986 0.33748682 0.32827332]
[0.33424011 0.33747957 0.32828032]
[0.33424034 0.33747233 0.32828732]
[0.33424058 0.33746511 0.32829431]
[0.33424081 0.3374579  0.32830129]
[0.33424104 0.3374507  0.32830826]
[0.33424127 0.337443

[0.33410397 0.33488153 0.33101451]
[0.33410347 0.33487869 0.33101784]
[0.33410297 0.33487586 0.33102118]
[0.33410247 0.33487303 0.3310245 ]
[0.33410197 0.3348702  0.33102783]
[0.33410147 0.33486739 0.33103115]
[0.33410096 0.33486457 0.33103446]
[0.33410046 0.33486176 0.33103777]
[0.33409996 0.33485896 0.33104108]
[0.33409946 0.33485616 0.33104438]
[0.33409895 0.33485337 0.33104768]
[0.33409845 0.33485058 0.33105097]
[0.33409795 0.33484779 0.33105426]
[0.33409744 0.33484502 0.33105754]
[0.33409694 0.33484224 0.33106082]
[0.33409644 0.33483947 0.33106409]
[0.33409593 0.33483671 0.33106736]
[0.33409543 0.33483395 0.33107063]
[0.33409492 0.33483119 0.33107389]
[0.33409442 0.33482844 0.33107714]
[0.33409391 0.33482569 0.3310804 ]
[0.3340934  0.33482295 0.33108364]
[0.3340929  0.33482022 0.33108689]
[0.33409239 0.33481748 0.33109012]
[0.33409188 0.33481476 0.33109336]
[0.33409138 0.33481203 0.33109659]
[0.33409087 0.33480932 0.33109981]
[0.33409036 0.3348066  0.33110303]
[0.33408985 0.334803

[0.33385966 0.3339666  0.33217374]
[0.33385917 0.33396537 0.33217546]
[0.33385868 0.33396414 0.33217718]
[0.3338582  0.33396291 0.33217889]
[0.33385771 0.33396169 0.3321806 ]
[0.33385722 0.33396047 0.33218231]
[0.33385673 0.33395925 0.33218402]
[0.33385625 0.33395803 0.33218572]
[0.33385576 0.33395682 0.33218742]
[0.33385527 0.3339556  0.33218912]
[0.33385479 0.33395439 0.33219082]
[0.3338543  0.33395319 0.33219251]
[0.33385382 0.33395198 0.3321942 ]
[0.33385333 0.33395078 0.33219589]
[0.33385284 0.33394957 0.33219758]
[0.33385236 0.33394838 0.33219927]
[0.33385187 0.33394718 0.33220095]
[0.33385139 0.33394598 0.33220263]
[0.33385091 0.33394479 0.3322043 ]
[0.33385042 0.3339436  0.33220598]
[0.33384994 0.33394241 0.33220765]
[0.33384945 0.33394122 0.33220932]
[0.33384897 0.33394004 0.33221099]
[0.33384849 0.33393886 0.33221266]
[0.333848   0.33393768 0.33221432]
[0.33384752 0.3339365  0.33221598]
[0.33384704 0.33393532 0.33221764]
[0.33384656 0.33393415 0.33221929]
[0.33384607 0.333932

[0.33366083 0.33357873 0.33276044]
[0.33366048 0.33357821 0.33276131]
[0.33366012 0.3335777  0.33276218]
[0.33365977 0.33357718 0.33276305]
[0.33365941 0.33357667 0.33276392]
[0.33365906 0.33357615 0.33276479]
[0.33365871 0.33357564 0.33276565]
[0.33365836 0.33357513 0.33276652]
[0.333658   0.33357462 0.33276738]
[0.33365765 0.33357411 0.33276824]
[0.3336573 0.3335736 0.3327691]
[0.33365695 0.33357309 0.33276996]
[0.3336566  0.33357258 0.33277082]
[0.33365625 0.33357207 0.33277168]
[0.33365589 0.33357157 0.33277254]
[0.33365554 0.33357107 0.33277339]
[0.33365519 0.33357056 0.33277424]
[0.33365484 0.33357006 0.3327751 ]
[0.3336545  0.33356956 0.33277595]
[0.33365415 0.33356906 0.3327768 ]
[0.3336538  0.33356856 0.33277764]
[0.33365345 0.33356806 0.33277849]
[0.3336531  0.33356756 0.33277934]
[0.33365275 0.33356707 0.33278018]
[0.33365241 0.33356657 0.33278102]
[0.33365206 0.33356608 0.33278187]
[0.33365171 0.33356558 0.33278271]
[0.33365136 0.33356509 0.33278355]
[0.33365102 0.3335646  

[0.33352961 0.33342269 0.3330477 ]
[0.33352938 0.33342248 0.33304814]
[0.33352915 0.33342226 0.33304859]
[0.33352892 0.33342205 0.33304903]
[0.33352868 0.33342184 0.33304948]
[0.33352845 0.33342162 0.33304992]
[0.33352822 0.33342141 0.33305036]
[0.33352799 0.3334212  0.33305081]
[0.33352776 0.33342099 0.33305125]
[0.33352753 0.33342078 0.33305169]
[0.3335273  0.33342057 0.33305213]
[0.33352707 0.33342036 0.33305257]
[0.33352684 0.33342015 0.33305301]
[0.33352662 0.33341994 0.33305344]
[0.33352639 0.33341973 0.33305388]
[0.33352616 0.33341952 0.33305432]
[0.33352593 0.33341932 0.33305475]
[0.3335257  0.33341911 0.33305519]
[0.33352547 0.3334189  0.33305562]
[0.33352525 0.33341869 0.33305606]
[0.33352502 0.33341849 0.33305649]
[0.33352479 0.33341828 0.33305693]
[0.33352456 0.33341808 0.33305736]
[0.33352434 0.33341787 0.33305779]
[0.33352411 0.33341767 0.33305822]
[0.33352389 0.33341746 0.33305865]
[0.33352366 0.33341726 0.33305908]
[0.33352343 0.33341706 0.33305951]
[0.33352321 0.333416

[0.3334418 0.3333573 0.3332009]
[0.33344166 0.33335723 0.33320111]
[0.33344152 0.33335715 0.33320132]
[0.33344139 0.33335708 0.33320154]
[0.33344125 0.333357   0.33320175]
[0.33344111 0.33335693 0.33320196]
[0.33344098 0.33335685 0.33320217]
[0.33344084 0.33335678 0.33320238]
[0.33344071 0.3333567  0.33320259]
[0.33344057 0.33335663 0.3332028 ]
[0.33344044 0.33335655 0.33320301]
[0.3334403  0.33335648 0.33320322]
[0.33344017 0.3333564  0.33320343]
[0.33344003 0.33335633 0.33320364]
[0.3334399  0.33335626 0.33320385]
[0.33343976 0.33335618 0.33320406]
[0.33343963 0.33335611 0.33320426]
[0.33343949 0.33335603 0.33320447]
[0.33343936 0.33335596 0.33320468]
[0.33343923 0.33335589 0.33320488]
[0.33343909 0.33335582 0.33320509]
[0.33343896 0.33335574 0.3332053 ]
[0.33343883 0.33335567 0.3332055 ]
[0.33343869 0.3333556  0.33320571]
[0.33343856 0.33335553 0.33320591]
[0.33343843 0.33335545 0.33320612]
[0.33343829 0.33335538 0.33320632]
[0.33343816 0.33335531 0.33320653]
[0.33343803 0.33335524 

[0.33338721 0.33333425 0.33327854]
[0.33338714 0.33333423 0.33327863]
[0.33338707 0.33333421 0.33327872]
[0.333387   0.3333342  0.33327881]
[0.33338693 0.33333418 0.3332789 ]
[0.33338685 0.33333416 0.33327899]
[0.33338678 0.33333414 0.33327908]
[0.33338671 0.33333412 0.33327917]
[0.33338664 0.3333341  0.33327926]
[0.33338657 0.33333408 0.33327935]
[0.3333865  0.33333406 0.33327944]
[0.33338643 0.33333404 0.33327953]
[0.33338636 0.33333402 0.33327962]
[0.33338629 0.333334   0.33327971]
[0.33338622 0.33333399 0.3332798 ]
[0.33338615 0.33333397 0.33327989]
[0.33338608 0.33333395 0.33327997]
[0.33338601 0.33333393 0.33328006]
[0.33338594 0.33333391 0.33328015]
[0.33338587 0.33333389 0.33328024]
[0.3333858  0.33333387 0.33328033]
[0.33338573 0.33333386 0.33328042]
[0.33338566 0.33333384 0.3332805 ]
[0.33338559 0.33333382 0.33328059]
[0.33338552 0.3333338  0.33328068]
[0.33338545 0.33333378 0.33328077]
[0.33338538 0.33333376 0.33328086]
[0.33338531 0.33333375 0.33328094]
[0.33338524 0.333333

[0.33336138 0.33332955 0.33330907]
[0.33336134 0.33332955 0.33330911]
[0.3333613  0.33332954 0.33330915]
[0.33336126 0.33332954 0.3333092 ]
[0.33336123 0.33332954 0.33330924]
[0.33336119 0.33332953 0.33330928]
[0.33336115 0.33332953 0.33330932]
[0.33336111 0.33332953 0.33330936]
[0.33336107 0.33332953 0.3333094 ]
[0.33336103 0.33332952 0.33330944]
[0.333361   0.33332952 0.33330948]
[0.33336096 0.33332952 0.33330953]
[0.33336092 0.33332951 0.33330957]
[0.33336088 0.33332951 0.33330961]
[0.33336084 0.33332951 0.33330965]
[0.33336081 0.33332951 0.33330969]
[0.33336077 0.3333295  0.33330973]
[0.33336073 0.3333295  0.33330977]
[0.33336069 0.3333295  0.33330981]
[0.33336065 0.33332949 0.33330985]
[0.33336062 0.33332949 0.33330989]
[0.33336058 0.33332949 0.33330993]
[0.33336054 0.33332949 0.33330997]
[0.3333605  0.33332948 0.33331001]
[0.33336047 0.33332948 0.33331005]
[0.33336043 0.33332948 0.33331009]
[0.33336039 0.33332948 0.33331013]
[0.33336035 0.33332947 0.33331017]
[0.33336032 0.333329

[0.33334722 0.33332951 0.33332327]
[0.3333472  0.33332952 0.33332328]
[0.33334718 0.33332952 0.3333233 ]
[0.33334716 0.33332952 0.33332332]
[0.33334714 0.33332952 0.33332334]
[0.33334712 0.33332952 0.33332336]
[0.3333471  0.33332952 0.33332337]
[0.33334708 0.33332953 0.33332339]
[0.33334706 0.33332953 0.33332341]
[0.33334704 0.33332953 0.33332343]
[0.33334702 0.33332953 0.33332345]
[0.333347   0.33332953 0.33332346]
[0.33334698 0.33332953 0.33332348]
[0.33334697 0.33332954 0.3333235 ]
[0.33334695 0.33332954 0.33332352]
[0.33334693 0.33332954 0.33332353]
[0.33334691 0.33332954 0.33332355]
[0.33334689 0.33332954 0.33332357]
[0.33334687 0.33332955 0.33332359]
[0.33334685 0.33332955 0.3333236 ]
[0.33334683 0.33332955 0.33332362]
[0.33334681 0.33332955 0.33332364]
[0.33334679 0.33332955 0.33332366]
[0.33334677 0.33332955 0.33332367]
[0.33334675 0.33332956 0.33332369]
[0.33334673 0.33332956 0.33332371]
[0.33334671 0.33332956 0.33332373]
[0.3333467  0.33332956 0.33332374]
[0.33334668 0.333329

[0.33334017 0.33333059 0.33332925]
[0.33334016 0.33333059 0.33332926]
[0.33334015 0.33333059 0.33332926]
[0.33334014 0.33333059 0.33332927]
[0.33334013 0.33333059 0.33332928]
[0.33334012 0.3333306  0.33332929]
[0.33334011 0.3333306  0.33332929]
[0.3333401 0.3333306 0.3333293]
[0.33334009 0.3333306  0.33332931]
[0.33334008 0.33333061 0.33332932]
[0.33334007 0.33333061 0.33332933]
[0.33334006 0.33333061 0.33332933]
[0.33334005 0.33333061 0.33332934]
[0.33334004 0.33333062 0.33332935]
[0.33334003 0.33333062 0.33332936]
[0.33334002 0.33333062 0.33332936]
[0.33334001 0.33333062 0.33332937]
[0.33334    0.33333062 0.33332938]
[0.33333999 0.33333063 0.33332939]
[0.33333998 0.33333063 0.33332939]
[0.33333997 0.33333063 0.3333294 ]
[0.33333996 0.33333063 0.33332941]
[0.33333995 0.33333064 0.33332942]
[0.33333994 0.33333064 0.33332942]
[0.33333993 0.33333064 0.33332943]
[0.33333992 0.33333064 0.33332944]
[0.33333991 0.33333065 0.33332945]
[0.3333399  0.33333065 0.33332945]
[0.33333989 0.33333065 

[0.33333616 0.33333178 0.33333206]
[0.33333616 0.33333178 0.33333207]
[0.33333615 0.33333178 0.33333207]
[0.33333615 0.33333178 0.33333207]
[0.33333614 0.33333178 0.33333207]
[0.33333614 0.33333179 0.33333208]
[0.33333613 0.33333179 0.33333208]
[0.33333613 0.33333179 0.33333208]
[0.33333613 0.33333179 0.33333208]
[0.33333612 0.33333179 0.33333209]
[0.33333612 0.33333179 0.33333209]
[0.33333611 0.33333179 0.33333209]
[0.33333611 0.3333318  0.33333209]
[0.33333611 0.3333318  0.3333321 ]
[0.3333361 0.3333318 0.3333321]
[0.3333361 0.3333318 0.3333321]
[0.33333609 0.3333318  0.3333321 ]
[0.33333609 0.3333318  0.33333211]
[0.33333608 0.33333181 0.33333211]
[0.33333608 0.33333181 0.33333211]
[0.33333608 0.33333181 0.33333211]
[0.33333607 0.33333181 0.33333212]
[0.33333607 0.33333181 0.33333212]
[0.33333606 0.33333181 0.33333212]
[0.33333606 0.33333182 0.33333212]
[0.33333605 0.33333182 0.33333213]
[0.33333605 0.33333182 0.33333213]
[0.33333605 0.33333182 0.33333213]
[0.33333604 0.33333182 0.3

[0.33333455 0.33333249 0.33333296]
[0.33333455 0.3333325  0.33333296]
[0.33333454 0.3333325  0.33333296]
[0.33333454 0.3333325  0.33333296]
[0.33333454 0.3333325  0.33333296]
[0.33333454 0.3333325  0.33333296]
[0.33333454 0.3333325  0.33333296]
[0.33333453 0.3333325  0.33333296]
[0.33333453 0.3333325  0.33333296]
[0.33333453 0.3333325  0.33333297]
[0.33333453 0.3333325  0.33333297]
[0.33333453 0.33333251 0.33333297]
[0.33333453 0.33333251 0.33333297]
[0.33333452 0.33333251 0.33333297]
[0.33333452 0.33333251 0.33333297]
[0.33333452 0.33333251 0.33333297]
[0.33333452 0.33333251 0.33333297]
[0.33333452 0.33333251 0.33333297]
[0.33333451 0.33333251 0.33333297]
[0.33333451 0.33333251 0.33333297]
[0.33333451 0.33333251 0.33333298]
[0.33333451 0.33333251 0.33333298]
[0.33333451 0.33333252 0.33333298]
[0.33333451 0.33333252 0.33333298]
[0.3333345  0.33333252 0.33333298]
[0.3333345  0.33333252 0.33333298]
[0.3333345  0.33333252 0.33333298]
[0.3333345  0.33333252 0.33333298]
[0.3333345  0.333332

[0.33333381 0.33333293 0.33333326]
[0.33333381 0.33333293 0.33333326]
[0.33333381 0.33333293 0.33333326]
[0.33333381 0.33333293 0.33333326]
[0.33333381 0.33333293 0.33333326]
[0.33333381 0.33333293 0.33333326]
[0.33333381 0.33333293 0.33333326]
[0.3333338  0.33333293 0.33333326]
[0.3333338  0.33333293 0.33333327]
[0.3333338  0.33333293 0.33333327]
[0.3333338  0.33333293 0.33333327]
[0.3333338  0.33333293 0.33333327]
[0.3333338  0.33333293 0.33333327]
[0.3333338  0.33333293 0.33333327]
[0.3333338  0.33333293 0.33333327]
[0.3333338  0.33333293 0.33333327]
[0.3333338  0.33333294 0.33333327]
[0.3333338  0.33333294 0.33333327]
[0.3333338  0.33333294 0.33333327]
[0.3333338  0.33333294 0.33333327]
[0.33333379 0.33333294 0.33333327]
[0.33333379 0.33333294 0.33333327]
[0.33333379 0.33333294 0.33333327]
[0.33333379 0.33333294 0.33333327]
[0.33333379 0.33333294 0.33333327]
[0.33333379 0.33333294 0.33333327]
[0.33333379 0.33333294 0.33333327]
[0.33333379 0.33333294 0.33333327]
[0.33333379 0.333332

[0.33333351 0.33333315 0.33333334]
[0.33333351 0.33333315 0.33333334]
[0.33333351 0.33333315 0.33333334]
[0.33333351 0.33333315 0.33333334]
[0.33333351 0.33333315 0.33333334]
[0.33333351 0.33333315 0.33333334]
[0.33333351 0.33333315 0.33333334]
[0.33333351 0.33333315 0.33333334]
[0.33333351 0.33333315 0.33333334]
[0.33333351 0.33333315 0.33333334]
[0.33333351 0.33333315 0.33333334]
[0.33333351 0.33333315 0.33333334]
[0.33333351 0.33333315 0.33333334]
[0.33333351 0.33333315 0.33333334]
[0.33333351 0.33333315 0.33333334]
[0.33333351 0.33333315 0.33333334]
[0.33333351 0.33333315 0.33333334]
[0.33333351 0.33333315 0.33333334]
[0.33333351 0.33333315 0.33333334]
[0.33333351 0.33333315 0.33333334]
[0.33333351 0.33333315 0.33333334]
[0.33333351 0.33333315 0.33333334]
[0.33333351 0.33333315 0.33333334]
[0.33333351 0.33333315 0.33333334]
[0.33333351 0.33333315 0.33333334]
[0.33333351 0.33333315 0.33333334]
[0.33333351 0.33333315 0.33333334]
[0.33333351 0.33333315 0.33333334]
[0.33333351 0.333333

[0.3333334  0.33333325 0.33333335]
[0.3333334  0.33333325 0.33333335]
[0.3333334  0.33333325 0.33333335]
[0.3333334  0.33333325 0.33333335]
[0.33333339 0.33333325 0.33333335]
[0.33333339 0.33333325 0.33333335]
[0.33333339 0.33333325 0.33333335]
[0.33333339 0.33333325 0.33333335]
[0.33333339 0.33333325 0.33333335]
[0.33333339 0.33333325 0.33333335]
[0.33333339 0.33333325 0.33333335]
[0.33333339 0.33333325 0.33333335]
[0.33333339 0.33333325 0.33333335]
[0.33333339 0.33333325 0.33333335]
[0.33333339 0.33333326 0.33333335]
[0.33333339 0.33333326 0.33333335]
[0.33333339 0.33333326 0.33333335]
[0.33333339 0.33333326 0.33333335]
[0.33333339 0.33333326 0.33333335]
[0.33333339 0.33333326 0.33333335]
[0.33333339 0.33333326 0.33333335]
[0.33333339 0.33333326 0.33333335]
[0.33333339 0.33333326 0.33333335]
[0.33333339 0.33333326 0.33333335]
[0.33333339 0.33333326 0.33333335]
[0.33333339 0.33333326 0.33333335]
[0.33333339 0.33333326 0.33333335]
[0.33333339 0.33333326 0.33333335]
[0.33333339 0.333333